### PR TITLE
Remove useless public in Unit Test

### PR DESCRIPTION
**Pull request by jackwener**
## *Important Read*
- *Please ensure the GitHub issue is mentioned at the beginning of the PR*

## What is the purpose of the pull request

Remove useless public in Unit Test

## Brief change log

Remove useless public in Unit Test

## Verify this pull request

*(Please pick either of the following options)*

This pull request is a trivial rework / code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

- *Added integration tests for end-to-end.*
- *Added HudiSchemaEvolutionTest to verify the change.*
- *Manually verified the change by running a job locally.*

### CODE REVIEW

**Review by ashvina — COMMENTED** [review]
Hi @jackwener
I appreciate the changes you made. However, I have a question. How can we prevent the code from diverging again, since the tests' access modifier is not automatically enforced? The IDE's default behavior is to add the public modifier. I would also like to know the reason and the benefits of enforcing this rule.

**Comment by jackwener** [comment]
Since JUnit 5, test methods no longer need to be explicitly declared as public. This is because JUnit 5 uses reflection to invoke test methods, which doesn't require the methods to be public. Therefore, having them with the default access modifier (i.e., package-private) is sufficient. 

SonarLint will suggest removing unnecessary public modifiers.

**Comment by jackwener** [comment]
I also agree that this change is not necessary. If the maintainer feels that this is an unnecessary PR and decides to close it, I also can understand.

**Comment by ashvina** [comment]
> I also agree that this change is not necessary. If the maintainer feels that this is an unnecessary PR and decides to close it, I also can understand.

Hi @jackwener 
Apologies for the misunderstanding. I didn't mean to suggest that the PR is unnecessary; in fact, I meant the contrary. Although I did come across some articles about the modifier, I couldn't find the underlying rationale for it. Without this, it's challenging to assess its importance. Also, my worry is that without any enforcement, the code may start to deviate again.

**Comment by the-other-tim-brown** [comment]
@jackwener Is there any way to add this to our spotless plugin? That would be an easy way to enforce it on future changes

**Comment by jackwener** [comment]
> Also, my worry is that without any enforcement, the code may start to deviate again.

Sorry for the misunderstanding.

> Is there any way to add this to our spotless plugin? 

Spotless primarily focuses on code formatting, such as indentation, spacing, and line breaks, rather than the code's structure or syntax. So spotless can't enforce it.

**Pull request closed without merging**
